### PR TITLE
fix: issue #120

### PR DESCRIPTION
**Pull request by yoution**

### CODE REVIEW

**Comment by yoution** [comment]
@maxceem please review

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution looks good. Can we just make the option labels same capitalized format like here. Please, don't make it lowercase.

image

**Comment by maxceem** [comment]
One more thing @yoution. When we view the job, it should show the not the value, but the label:

image

it should be `Software Developer` - label here.

**Comment by yoution** [comment]
@maxceem please review

**Review by maxceem — CHANGES_REQUESTED** [review]
Thanks @yoution.

There is one more place where we have to show the label for the Resource Type instead of the value.
When we view Job:

image

**Comment by yoution** [comment]
@maxceem please review

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution in some cases we might have a value here which is not listed in the Options.

In such cases we are showing like this:

image

This already works good for edit form.

But in View mode it showing nothing 

image

But actually, we have a value there, it is just not supported by select.

We already have a reusable method that can return option, and it also supports showing unsupported value. So this code:
```js
{_.get(
                  _.find(
                    RESOURCE_TYPE_OPTIONS,
                    (t) => t.value === job.resourceType
                  ),
                  "label"
                )}
```

Could be replaced with something like:
```js
_.get(getSelectOptionByValue(job.resourceType, RESOURCE_TYPE_OPTIONS), 'label')
```

**Review by maxceem — APPROVED** [review]
Everything works perfectly now. Thank you for the updates @yoution.

**Pull request merged**
