### PR TITLE
fix: issue #13

### PR DESCRIPTION
**Pull request by yoution**
@maxceem please reivew for #13

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution it has some issue for me.

I've added some fix to the `config` to be able to test locally. You may apply your changes to the branch `feature/build-improvements` where config is fixed, and after make the next commands to test your PR locally.

1. If I build in production mode the styles got broken:

    - build `APPMODE=production APPENV=dev npm run build`
    - host the built files: `npx http-server dist -p 8501 --cors`
    - open http://localhost:8080/taas/myteams
    - styles got broken 
    
       image
       
2. If I build in development mode the styles got broken too:

    - build `APPMODE=development APPENV=dev npm run build`
    - host the built files: `npx http-server dist -p 8501 --cors`
    - open http://localhost:8080/taas/myteams
    - styles got broken 
    
       image

**Comment by yoution** [comment]
@maxceem  for `APPMODE=development APPENV=dev npm run build`, maybe some cache, you should disabled the cache,
I have pushed, please review #13

**Comment by maxceem** [comment]
> I have pushed, please review #13

@yoution I don't see new changes in the PR.

Did you try to run it locally? Can you please share a demo video of how it works for you? See how it works for me after I apply the fix from branch `feature/build-improvements` and your PR, video https://monosnap.com/file/ljk5UEeTntl9dvJp6oYluuanwvRh7V

**Comment by maxceem** [comment]
Closing this PR as a new one was created https://github.com/topcoder-platform/taas-app/pull/58

**Comment by yoution** [comment]
@maxceem #58 still not work? I change file in the `webpack.js` file, I will record a video

**Comment by maxceem** [comment]
I will check #58 now, didn't check it yet.

**Comment by yoution** [comment]
@maxceem  https://monosnap.com/file/fHzGiPGPIumKvOalNARgYy9Lz6E9l2

**Comment by maxceem** [comment]
@yoution it seems to work good now, no need to create a video.

**Pull request closed without merging**
