### PR TITLE
fix issue topcoder-platform/taas-apis#507

### PR DESCRIPTION
**Pull request by yoution**
@maxceem please review

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
Thanks @yoution 

In one place I've noticed the job format has been changed:

image

**Comment by yoution** [comment]
@maxceem I didnot change the code, 
does it need to change to `yyyy-mm-dd` ? 
image

**Comment by maxceem** [comment]
@yoution No the job start date format should be `09/27/2020` but now it's changed to `2020-09-27`

image

**Comment by yoution** [comment]
image

**Review by maxceem — APPROVED** [review]
Thanks @yoution all great now.

**Pull request merged**
