### PR TITLE
feat: add https for link dialog

### PR DESCRIPTION
**Pull request by yoution**

### CODE REVIEW

**Comment by yoution** [comment]
@maxceem  please reivew.
how about this way?   https://monosnap.com/file/RMxDtAcjcdh0ZzQxbY7l8GfVR8mbUv
currently, there is no hooks for this issue. https://github.com/nhn/tui.editor/issues/1096

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution thank you for providing a demo video. Yeah, I saw that ticket nhn/tui.editor#1096.

The way you suggest the user still can remove `https://` and then link would get broken. We have to make sure that links are never get broken.

There is some idea, but not sure if it would work: can we process the value of the editor and if there is link without `http(s)` we fix it in the value. But we have to make sure that we don't process the value on every change or it would be very slow, for example we can try processing it after user closes Add Link Popup:
- I can see you use `openPopupAddLink` is there event on close the event popup `closePopupAddLink`?
- if we have such event what we can try to do is the next:
  - when link popup is closed `closePopupAddLink` 
  - we can get the current value of the editor and parse all the link in markdow `[link text](test.com)`
  - if we find some link without `http`/`https` we have to add it: `[link text](https://test.com)`
  - after this we have to update the value inside the editor
  - and call `onChange` callback with the updated value

What do you think could this work?

**Comment by maxceem** [comment]
hey @yoution looks I've found a good place for the logic to update links: https://github.com/nhn/tui.editor/blob/master/apps/editor/src/js/convertor.js#L167

Looks like this event is called during [getMarkdown()](https://github.com/topcoder-platform/taas-app/blob/dev/src/components/MarkdownEditor/index.jsx#L15).

So all we need, is to subscribe to `convertorAfterHtmlToMarkdownConverted` and in the event handler, find all the links `[link text](test.com)` and if link doesn't have `http` or `https`, then add it and return the whole update markdown.

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution let's try to use your approach with `command` event, not mine for now.

Could you please, ever the last commit with the approach suggested by me?

**Update:** please ignore this, it works good.

~And there is one issue in your approach, if I enter link with `http` it looses `http`, see demo video https://monosnap.com/file/QEFjyHWLe3B6kHT8j5jtdEht9i4iuU.

Other case seems to work fine, but I would test more.~

**Comment by yoution** [comment]
@maxceem please review

**Comment by maxceem** [comment]
@yoution your solution works great. I've tested yours and mine, it was hard to decide which one is better as each solution has benefits and drawback. At the end I decided to use my solution, because it looks like uses official features of tuiEditor, I'm a little bit afraid of using solution where we need to change th order of events, as maybe tuiEditor change something in the next version and it would stop working.

Anyway, you found a good workable solution, so I've processed the payment https://www.topcoder.com/challenges/4d40a5ab-21b8-46aa-888e-de5f33e54df5.

Maybe we would use your solution one day if we find some issue with mine.

**Pull request closed without merging**
