### PR TITLE
fix: issue #138

### PR DESCRIPTION
**Pull request by yoution**
@maxceem please review

### CODE REVIEW

**Comment by yoution** [comment]
@maxceem please review

**Comment by maxceem** [comment]
sorry for the delay @yoution I will do it today

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution in general it works as expected, though there are a couple of visual fixes:

1. Let's make all the disabled fields look the same way. Make all the fields look like "Job Name" when it's disabled.

   image

2. When the Job Description is disabled because of "status" we should not show the red warning. We should only show this red warning when `isApplicationPageActive === true`.


   image

**Review by maxceem — CHANGES_REQUESTED** [review]
Thanks @yoution the styles look great now.

I've missed one thing in the review before. When the skills select is disabled, can we hide the `x` buttons as we cannot remove these fields?

image

**Review by maxceem — APPROVED** [review]
Works great now. Thank you @yoution.

**Pull request merged**
