### PR TITLE
fix: issue #90

### PR DESCRIPTION
**Pull request by yoution**

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution we would like to use API for loading a single Job for this by id https://github.com/topcoder-platform/taas-app/blob/dev/src/services/jobs.js#L9-L16.

In your implementation, you are using an endpoint to get the whole Team. Such an endpoint returns much more data and is slower than loading a single Job.
Also, we don't have to load Job, if resource booking doesn't have `jobId`. While now, you are always loading the Team data.

Though what we can change in the initial requirement is:
- it's ok to load resource booking first, and show `Loading...` inside Job Name, if the job not yet loaded, and only show job name after it is loaded
- or wait until job is loaded as was required initially
both ways are fine.

**Comment by yoution** [comment]
@maxceem how can I get these info
image

from the  `resourcebooking` api, I can not get these info

**Comment by maxceem** [comment]
I've got you @yoution. Let's hold on a bit with this task. We would have to update the API before we can fix this task.

**Review by maxceem — APPROVED** [review]
@yoution I guess we cannot update API for this fast, but we need this fix asap. So we would use your approach here. Great finding of using Team endpoint for this, by the way. Thank you.

**Pull request merged**
