### PR TITLE
Fixed issue with job candidates not moving to correct tab after scheduling interviews.

### PR DESCRIPTION
**Pull request by mahidulalvi-bonic**
This works by reloading the job position details from the API after an interview is scheduled with a candidate.

Changes for issue https://github.com/topcoder-platform/taas-app/issues/546.

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
hey @mahidulalvi-bonic it doesn't work for me.

If I open any position page I see loading forever:

image

Example URL https://platform.topcoder-dev.com/taas/myteams/18971/positions/29b37350-daa7-4ca2-87c4-19ee966002fc/candidates/interviews

Also, I've noticed that you've introduced a new action to reload position data. Though I'm not sure what is benefit of it.
Could we just directly call existent method `loadPosition` when interview is confirmed?
So instead of `dispatch(triggerPositionDataRefresh());` just directly call `dispatch(loadPosition(teamId, positionId));`? Or is there any blockers?

**Comment by mahidulalvi-bonic** [comment]
Hi @maxceem, the new action doesn’t reload the data, instead it enables a flag in the position object in redux state, so the hook responsible for loading position data loads that data upon detecting that flag. I found it least amount of work so but there are other ways as well which may need refactoring. 

Source hooks file (https://github.com/topcoder-platform/taas-app/blob/15f77441d1a39d9d09cc1b9d37763c05f6107c8d/src/routes/PositionDetails/hooks/useTeamPositionsState.js).

For the loading error, is it possible to give me the browser console log?

**Comment by maxceem** [comment]
@mahidulalvi-bonic here is the video showing how it looks like including console https://monosnap.com/file/6M9d0OqtcpXUWdKcM9AbLrwimlwqgr

If you check the 8th second, the screen blinks and shows Job Candidates for one moment, and then continues loading

image

> the new action doesn’t reload the data, instead it enables a flag in the position object in redux state, so the hook responsible for loading position data loads that data upon detecting that flag.

Yeah, I've got the logic, though adding such a flag feels a bit hacky. As we already have method to reload data for the page and could directly call it. I would avoid adding such a flag, unless there are some strong reasons.

>  I found it least amount of work so but there are other ways as well which may need refactoring.

What do you think has to be refactored? Is it more than dispatching `loadPosition`?

**Comment by mahidulalvi-bonic** [comment]
@maxceem, I found the issue with loading screen, I pushed a commit for the fix in this PR.

For the refactoring tasks, now that I look into it, I may have misread the variable `useTeamPositionsState` as a custom useState but turns out its only a store subscribed value. So theoretically dispatching loadPosition should work. Just need to pass the teamId and positionId to where the function would be called from.

**Comment by maxceem** [comment]
@mahidulalvi-bonic yeah, I would definitely prefer just calling `loadPosition` because adding such a flag feels like a workaround which adds more code to support which is not necessary.

**Comment by mahidulalvi-bonic** [comment]
@maxceem, I updated the PR with the latest changes, it should work now. Please let me know.

**Review by maxceem — CHANGES_REQUESTED** [review]
@mahidulalvi-bonic almost perfect now.

There is one small thing:
- when we schedule interview we are showing a loading indicator, this indicator should be shown until we reload data for the position. Because now, we stop showing indicator, and position details are updated after that. If internet connection is slower, it could happen that we schedule interview, close modal, and still see interview in the list.
- so loading indicator should be shown until we update interview in the list

See demo video - interview disappears after the loading indicator is hidden https://monosnap.com/file/HOPpPMtF64YGOzwNvRKn9BsP9cZqwQ

Note, that `dispatch(loadPosition(teamId, positionId))` is a Promise, so you may easily wait until this operation is complete, and hide loading indicator after that.

If you have any questions regarding this, please, let me know.

**Comment by mahidulalvi-bonic** [comment]
@maxceem, I updated the PR. Can you please confirm?

**Review by maxceem — APPROVED** [review]
Thank you, @mahidulalvi-bonic works good now, passing for QA.

**Pull request merged**
