### PR TITLE
fix: issue #562

### PR DESCRIPTION
**Pull request by yoution**
@maxceem please review

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution works good, but the font is different, could we fix the font?

image

**Comment by yoution** [comment]
which browse do you use?
which font do we need?

**Comment by maxceem** [comment]
I use Google Chrome on macOS.

We need the same font Nylas us in their page I guess this one https://monosnap.com/file/GA18Q8gndb1qnyLAmKzWz9PN9KvH8k

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution it still looks different from the real page.

Please, see the video https://monosnap.com/file/ZIGfEfLkmj3CIYPSYRXaVX25nKi3bF

Can we make the styles the same? So when this page is shown it looks like a real page?

To get styles from the real page, you may select a time on this page https://schedule.nylas.com/tc-taas-interview-70e34e1e-cff6-4483-93dc-2e3923658578 and you would see the real page. So you could gram the exact styles.

Also, could we please show the Checkmark to make it the same https://monosnap.com/file/hLAoDw8sJBVTwdQEqhcXmGx3nqIX1S

**Review by maxceem — APPROVED** [review]
@yoution looks good. Merging for QA.

**Pull request merged**
